/***
 * Demonstrike Core
 */

#pragma once

#define ITEM_NO_SLOT_AVAILABLE -1 //works for all kind of slots now
#define INVENTORY_SLOT_NOT_SET -1

#define MAX_BUYBACK_SLOT 13
#define MAX_INVENTORY_SLOT 118

enum ItemSlots
{
    EQUIPMENT_SLOT_START = 0,
    EQUIPMENT_SLOT_HEAD = 0,
    EQUIPMENT_SLOT_NECK,
    EQUIPMENT_SLOT_SHOULDERS,
    EQUIPMENT_SLOT_BODY,
    EQUIPMENT_SLOT_CHEST,
    EQUIPMENT_SLOT_WAIST,
    EQUIPMENT_SLOT_LEGS,
    EQUIPMENT_SLOT_FEET,
    EQUIPMENT_SLOT_WRISTS,
    EQUIPMENT_SLOT_HANDS,
    EQUIPMENT_SLOT_FINGER1,
    EQUIPMENT_SLOT_FINGER2,
    EQUIPMENT_SLOT_TRINKET1,
    EQUIPMENT_SLOT_TRINKET2,
    EQUIPMENT_SLOT_BACK,
    EQUIPMENT_SLOT_MAINHAND,
    EQUIPMENT_SLOT_OFFHAND,
    EQUIPMENT_SLOT_RANGED,
    EQUIPMENT_SLOT_TABARD,
    EQUIPMENT_SLOT_END,

    INVENTORY_SLOT_BAG_START = 19,
    INVENTORY_SLOT_BAG_1 = 19,
    INVENTORY_SLOT_BAG_2,
    INVENTORY_SLOT_BAG_3,
    INVENTORY_SLOT_BAG_4,
    INVENTORY_SLOT_BAG_END,

    INVENTORY_SLOT_ITEM_START = 23,
    INVENTORY_SLOT_ITEM_1 = 23,
    INVENTORY_SLOT_ITEM_2,
    INVENTORY_SLOT_ITEM_3,
    INVENTORY_SLOT_ITEM_4,
    INVENTORY_SLOT_ITEM_5,
    INVENTORY_SLOT_ITEM_6,
    INVENTORY_SLOT_ITEM_7,
    INVENTORY_SLOT_ITEM_8,
    INVENTORY_SLOT_ITEM_9,
    INVENTORY_SLOT_ITEM_10,
    INVENTORY_SLOT_ITEM_11,
    INVENTORY_SLOT_ITEM_12,
    INVENTORY_SLOT_ITEM_13,
    INVENTORY_SLOT_ITEM_14,
    INVENTORY_SLOT_ITEM_15,
    INVENTORY_SLOT_ITEM_16,
    INVENTORY_SLOT_ITEM_END,

    BANK_SLOT_ITEM_START = 39,
    BANK_SLOT_ITEM_1 = 39,
    BANK_SLOT_ITEM_2,
    BANK_SLOT_ITEM_3,
    BANK_SLOT_ITEM_4,
    BANK_SLOT_ITEM_5,
    BANK_SLOT_ITEM_6,
    BANK_SLOT_ITEM_7,
    BANK_SLOT_ITEM_8,
    BANK_SLOT_ITEM_9,
    BANK_SLOT_ITEM_10,
    BANK_SLOT_ITEM_11,
    BANK_SLOT_ITEM_12,
    BANK_SLOT_ITEM_13,
    BANK_SLOT_ITEM_14,
    BANK_SLOT_ITEM_15,
    BANK_SLOT_ITEM_16,
    BANK_SLOT_ITEM_17,
    BANK_SLOT_ITEM_18,
    BANK_SLOT_ITEM_19,
    BANK_SLOT_ITEM_20,
    BANK_SLOT_ITEM_21,
    BANK_SLOT_ITEM_22,
    BANK_SLOT_ITEM_23,
    BANK_SLOT_ITEM_24,
    BANK_SLOT_ITEM_25,
    BANK_SLOT_ITEM_26,
    BANK_SLOT_ITEM_27,
    BANK_SLOT_ITEM_28,
    BANK_SLOT_ITEM_END,

    BANK_SLOT_BAG_START = 67,
    BANK_SLOT_BAG_1 = 67,
    BANK_SLOT_BAG_2,
    BANK_SLOT_BAG_3,
    BANK_SLOT_BAG_4,
    BANK_SLOT_BAG_5,
    BANK_SLOT_BAG_6,
    BANK_SLOT_BAG_7,
    BANK_SLOT_BAG_END,

    INVENTORY_KEYRING_START = 86,
    INVENTORY_KEYRING_1 = 86,
    INVENTORY_KEYRING_2,
    INVENTORY_KEYRING_3,
    INVENTORY_KEYRING_4,
    INVENTORY_KEYRING_5,
    INVENTORY_KEYRING_6,
    INVENTORY_KEYRING_7,
    INVENTORY_KEYRING_8,
    INVENTORY_KEYRING_9,
    INVENTORY_KEYRING_10,
    INVENTORY_KEYRING_11,
    INVENTORY_KEYRING_12,
    INVENTORY_KEYRING_13,
    INVENTORY_KEYRING_14,
    INVENTORY_KEYRING_15,
    INVENTORY_KEYRING_16,
    INVENTORY_KEYRING_17,
    INVENTORY_KEYRING_18,
    INVENTORY_KEYRING_19,
    INVENTORY_KEYRING_20,
    INVENTORY_KEYRING_21,
    INVENTORY_KEYRING_22,
    INVENTORY_KEYRING_23,
    INVENTORY_KEYRING_24,
    INVENTORY_KEYRING_25,
    INVENTORY_KEYRING_26,
    INVENTORY_KEYRING_27,
    INVENTORY_KEYRING_28,
    INVENTORY_KEYRING_29,
    INVENTORY_KEYRING_30,
    INVENTORY_KEYRING_31,
    INVENTORY_KEYRING_32,
    INVENTORY_KEYRING_END
};

enum INV_ERR
{
    INV_ERR_OK = 0,
    INV_ERR_YOU_MUST_REACH_LEVEL_N,
    INV_ERR_SKILL_ISNT_HIGH_ENOUGH,
    INV_ERR_ITEM_DOESNT_GO_TO_SLOT,
    INV_ERR_BAG_FULL,
    INV_ERR_NONEMPTY_BAG_OVER_OTHER_BAG,
    INV_ERR_CANT_TRADE_EQUIP_BAGS,
    INV_ERR_ONLY_AMMO_CAN_GO_HERE,
    INV_ERR_NO_REQUIRED_PROFICIENCY,
    INV_ERR_NO_EQUIPMENT_SLOT_AVAILABLE,
    INV_ERR_YOU_CAN_NEVER_USE_THAT_ITEM,
    INV_ERR_YOU_CAN_NEVER_USE_THAT_ITEM2,
    INV_ERR_NO_EQUIPMENT_SLOT_AVAILABLE2,
    INV_ERR_CANT_EQUIP_WITH_TWOHANDED,
    INV_ERR_CANT_DUAL_WIELD,
    INV_ERR_ITEM_DOESNT_GO_INTO_BAG,
    INV_ERR_ITEM_DOESNT_GO_INTO_BAG2,
    INV_ERR_CANT_CARRY_MORE_OF_THIS,
    INV_ERR_NO_EQUIPMENT_SLOT_AVAILABLE3,
    INV_ERR_ITEM_CANT_STACK,
    INV_ERR_ITEM_CANT_BE_EQUIPPED,
    INV_ERR_ITEMS_CANT_BE_SWAPPED,
    INV_ERR_SLOT_IS_EMPTY,
    INV_ERR_ITEM_NOT_FOUND,
    INV_ERR_CANT_DROP_SOULBOUND,
    INV_ERR_OUT_OF_RANGE,
    INV_ERR_TRIED_TO_SPLIT_MORE_THAN_COUNT,
    INV_ERR_COULDNT_SPLIT_ITEMS,
    INV_ERR_MISSING_REAGENT,
    INV_ERR_NOT_ENOUGH_MONEY,
    INV_ERR_NOT_A_BAG,
    INV_ERR_CAN_ONLY_DO_WITH_EMPTY_BAGS,
    INV_ERR_DONT_OWN_THAT_ITEM,
    INV_ERR_CAN_EQUIP_ONLY1_QUIVER,
    INV_ERR_MUST_PURCHASE_THAT_BAG_SLOT,
    INV_ERR_TOO_FAR_AWAY_FROM_BANK,
    INV_ERR_ITEM_LOCKED,
    INV_ERR_YOU_ARE_STUNNED,
    INV_ERR_YOU_ARE_DEAD,
    INV_ERR_CANT_DO_RIGHT_NOW,
    INV_ERR_BAG_FULL2,
    INV_ERR_CAN_EQUIP_ONLY1_QUIVER2,
    INV_ERR_CAN_EQUIP_ONLY1_AMMOPOUCH,
    INV_ERR_STACKABLE_CANT_BE_WRAPPED,
    INV_ERR_EQUIPPED_CANT_BE_WRAPPED,
    INV_ERR_WRAPPED_CANT_BE_WRAPPED,
    INV_ERR_BOUND_CANT_BE_WRAPPED,
    INV_ERR_UNIQUE_CANT_BE_WRAPPED,
    INV_ERR_BAGS_CANT_BE_WRAPPED,
    INV_ERR_ALREADY_LOOTED,
    INV_ERR_INVENTORY_FULL,
    INV_ERR_BANK_FULL,
    INV_ERR_ITEM_IS_CURRENTLY_SOLD_OUT,
    INV_ERR_BAG_FULL3,
    INV_ERR_ITEM_NOT_FOUND2,
    INV_ERR_ITEM_CANT_STACK2,
    INV_ERR_BAG_FULL4,
    INV_ERR_ITEM_SOLD_OUT,
    INV_ERR_OBJECT_IS_BUSY,
    INV_ERR_NONE,
    INV_ERR_CANT_DO_IN_COMBAT,
    INV_ERR_CANT_DO_WHILE_DISARMED,
    INV_ERR_BAG_FULL6,
    INV_ERR_ITEM_RANK_NOT_ENOUGH,
    INV_ERR_ITEM_REPUTATION_NOT_ENOUGH,
    INV_ERR_MORE_THAN1_SPECIAL_BAG,
    INV_ERR_LOOT_CANT_LOOT_THAT_NOW,
    INV_ERR_ITEM_UNIQUE_EQUIPABLE,
    INV_ERR_VENDOR_MISSING_TURNINS,
    INV_ERR_NOT_ENOUGH_HONOR_POINTS,
    INV_ERR_NOT_ENOUGH_ARENA_POINTS,
    INV_ERR_ITEM_MAX_COUNT_SOCKETED,
    INV_ERR_MAIL_BOUND_ITEM,
    INV_ERR_NO_SPLIT_WHILE_PROSPECTING,
    INV_ERR_UNK,
    INV_ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED,
    INV_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED,
    INV_ERR_TOO_MUCH_GOLD,
    INV_ERR_NOT_DURING_ARENA_MATCH,
    INV_ERR_CANNOT_TRADE_THAT,
    INV_ERR_PERSONAL_ARENA_RATING_TOO_LOW,
    INV_ERR_EVENT_AUTOEQUIP_BIND_CONFIRM,
    INV_ERR_ACCOUNT_BOUND,
    INV_ERR_OK2,
    INV_ERR_ITEM_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED,
    INV_ERR_ITEM_MAX_LIMIT_CATEGORY_SOCKETED_EXCEEDED,
    INV_ERR_SCALING_STAT_ITEM_LEVEL_EXCEEDED,
    INV_ERR_PURCHASE_LEVEL_TOO_LOW,
    INV_ERR_CANT_EQUIP_NEED_TALENT,
    INV_ERR_ITEM_MAX_LIMIT_CATEGORY_EQUIPPED_EXCEEDED
};

enum ITEM_STAT_TYPE
{
    POWER                           = 0,
    HEALTH                          = 1,
    UNKNOWN                         = 2,
    AGILITY                         = 3,
    STRENGTH                        = 4,
    INTELLECT                       = 5,
    SPIRIT                          = 6,
    STAMINA                         = 7,
    WEAPON_SKILL_RATING             = 11,
    DEFENSE_RATING                  = 12,
    DODGE_RATING                    = 13,
    PARRY_RATING                    = 14,
    SHIELD_BLOCK_RATING             = 15,
    MELEE_HIT_RATING                = 16,
    RANGED_HIT_RATING               = 17,
    SPELL_HIT_RATING                = 18,
    MELEE_CRITICAL_STRIKE_RATING    = 19,
    RANGED_CRITICAL_STRIKE_RATING   = 20,
    SPELL_CRITICAL_STRIKE_RATING    = 21,
    MELEE_HIT_AVOIDANCE_RATING      = 22,
    RANGED_HIT_AVOIDANCE_RATING     = 23,
    SPELL_HIT_AVOIDANCE_RATING      = 24,
    MELEE_CRITICAL_AVOIDANCE_RATING = 25,
    RANGED_CRITICAL_AVOIDANCE_RATING= 26,
    SPELL_CRITICAL_AVOIDANCE_RATING = 27,
    MELEE_HASTE_RATING              = 28,
    RANGED_HASTE_RATING             = 29,
    SPELL_HASTE_RATING              = 30,
    HIT_RATING                      = 31,
    CRITICAL_STRIKE_RATING          = 32,
    HIT_AVOIDANCE_RATING            = 33,
    CRITICAL_AVOIDANCE_RATING       = 34,
    RESILIENCE_RATING               = 35,
    HASTE_RATING                    = 36,
    EXPERTISE_RATING                = 37,
    ATTACK_POWER                    = 38,
    RANGED_ATTACK_POWER             = 39,
    FERAL_ATTACK_POWER              = 40,
    SPELL_HEALING_DONE              = 41,
    SPELL_DAMAGE_DONE               = 42,
    MANA_REGENERATION               = 43,
    ARMOR_PENETRATION_RATING        = 44,
    SPELL_POWER                     = 45,
    HEALTH_REGEN                    = 46,
    SPELL_PENETRATION               = 47,
    BLOCK_VALUE                     = 48,
};


enum ITEM_DAMAGE_TYPE
{
    NORMAL_DAMAGE   = 0,
    HOLY_DAMAGE     = 1,
    FIRE_DAMAGE     = 2,
    NATURE_DAMAGE   = 3,
    FROST_DAMAGE    = 4,
    SHADOW_DAMAGE   = 5,
    ARCANE_DAMAGE   = 6,
};

enum ITEM_SPELLTRIGGER_TYPE
{
    USE             = 0,
    ON_EQUIP        = 1,
    CHANCE_ON_HIT   = 2,
    SOULSTONE       = 4,
    LEARNING        = 6,
};

enum ITEM_BONDING_TYPE
{
    ITEM_BIND_NONE      =   0,
    ITEM_BIND_ON_PICKUP =   1,
    ITEM_BIND_ON_EQUIP  =   2,
    ITEM_BIND_ON_USE    =   3,
    ITEM_BIND_QUEST     =   4,
    ITEM_BIND_QUEST2    =   5,
};

enum INVENTORY_TYPES
{
    INVTYPE_NON_EQUIP       = 0x0, // 0
    INVTYPE_HEAD            = 0x1, // 1
    INVTYPE_NECK            = 0x2, // 2
    INVTYPE_SHOULDERS       = 0x3, // 3
    INVTYPE_BODY            = 0x4, // 4
    INVTYPE_CHEST           = 0x5, // 5
    INVTYPE_WAIST           = 0x6, // 6 
    INVTYPE_LEGS            = 0x7, // 7
    INVTYPE_FEET            = 0x8, // 8
    INVTYPE_WRISTS          = 0x9, // 9
    INVTYPE_HANDS           = 0xa, // 10
    INVTYPE_FINGER          = 0xb, // 11
    INVTYPE_TRINKET         = 0xc, // 12
    INVTYPE_WEAPON          = 0xd, // 13
    INVTYPE_SHIELD          = 0xe, // 14
    INVTYPE_RANGED          = 0xf, // 15
    INVTYPE_CLOAK           = 0x10, //16
    INVTYPE_2HWEAPON        = 0x11, //17
    INVTYPE_BAG             = 0x12, //18
    INVTYPE_TABARD          = 0x13, //19
    INVTYPE_ROBE            = 0x14, //20
    INVTYPE_WEAPONMAINHAND  = 0x15, //21
    INVTYPE_WEAPONOFFHAND   = 0x16, //22
    INVTYPE_HOLDABLE        = 0x17, //23
    INVTYPE_AMMO            = 0x18, //24
    INVTYPE_THROWN          = 0x19, //25
    INVTYPE_RANGEDRIGHT     = 0x1a, //26
    INVTYPE_QUIVER          = 0x1b, //27
    INVTYPE_RELIC           = 0x1c, //28
    NUM_INVENTORY_TYPES     = 0x1d,
};

enum ITEM_CLASS
{
    ITEM_CLASS_CONSUMABLE   = 0,
    ITEM_CLASS_CONTAINER    = 1,
    ITEM_CLASS_WEAPON       = 2,
    ITEM_CLASS_JEWELRY      = 3,
    ITEM_CLASS_ARMOR        = 4,
    ITEM_CLASS_REAGENT      = 5,
    ITEM_CLASS_PROJECTILE   = 6,
    ITEM_CLASS_TRADEGOODS   = 7,
    ITEM_CLASS_GENERIC      = 8,
    ITEM_CLASS_RECIPE       = 9,
    ITEM_CLASS_MONEY        = 10,
    ITEM_CLASS_QUIVER       = 11,
    ITEM_CLASS_QUEST        = 12,
    ITEM_CLASS_KEY          = 13,
    ITEM_CLASS_PERMANENT    = 14,
    ITEM_CLASS_MISCELLANEOUS= 15,
    ITEM_CLASS_GLYPHS       = 16,
};

enum Item_Subclass
{
   // Weapon
   ITEM_SUBCLASS_WEAPON_AXE                 = 0,
   ITEM_SUBCLASS_WEAPON_TWOHAND_AXE         = 1,
   ITEM_SUBCLASS_WEAPON_BOW                 = 2,
   ITEM_SUBCLASS_WEAPON_GUN                 = 3,
   ITEM_SUBCLASS_WEAPON_MACE                = 4,
   ITEM_SUBCLASS_WEAPON_TWOHAND_MACE        = 5,
   ITEM_SUBCLASS_WEAPON_POLEARM             = 6,
   ITEM_SUBCLASS_WEAPON_SWORD               = 7,
   ITEM_SUBCLASS_WEAPON_TWOHAND_SWORD       = 8,
   ITEM_SUBCLASS_WEAPON_STAFF               = 10,
   ITEM_SUBCLASS_WEAPON_EXOTIC              = 11,
   ITEM_SUBCLASS_WEAPON_EXOTIC2             = 12,
   ITEM_SUBCLASS_WEAPON_FIST_WEAPON         = 13,
   ITEM_SUBCLASS_WEAPON_MISC_WEAPON         = 14,
   ITEM_SUBCLASS_WEAPON_DAGGER              = 15,
   ITEM_SUBCLASS_WEAPON_THROWN              = 16,
   ITEM_SUBCLASS_WEAPON_SPEAR               = 17,
   ITEM_SUBCLASS_WEAPON_CROSSBOW            = 18,
   ITEM_SUBCLASS_WEAPON_WAND                = 19,
   ITEM_SUBCLASS_WEAPON_FISHING_POLE        = 20,

   // Armor
   ITEM_SUBCLASS_ARMOR_MISC                 = 0,
   ITEM_SUBCLASS_ARMOR_CLOTH                = 1,
   ITEM_SUBCLASS_ARMOR_LEATHER              = 2,
   ITEM_SUBCLASS_ARMOR_MAIL                 = 3,
   ITEM_SUBCLASS_ARMOR_PLATE_MAIL           = 4,
   ITEM_SUBCLASS_ARMOR_BUCKLER              = 5,
   ITEM_SUBCLASS_ARMOR_SHIELD               = 6,
   ITEM_SUBCLASS_ARMOR_LIBRAM               = 7,
   ITEM_SUBCLASS_ARMOR_IDOL                 = 8,
   ITEM_SUBCLASS_ARMOR_TOTEM                = 9,
   ITEM_SUBCLASS_ARMOR_SIGIL                = 10,

   // Projectile
   ITEM_SUBCLASS_PROJECTILE_WAND            = 0,
   ITEM_SUBCLASS_PROJECTILE_BOLT            = 1,
   ITEM_SUBCLASS_PROJECTILE_ARROW           = 2,
   ITEM_SUBCLASS_PROJECTILE_BULLET          = 3,
   ITEM_SUBCLASS_PROJECTILE_THROWN          = 4,

   // Recipe
   ITEM_SUBCLASS_RECIPE_BOOK                = 0,
   ITEM_SUBCLASS_RECIPE_LEATHERWORKING      = 1,
   ITEM_SUBCLASS_RECIPE_TAILORING           = 2,
   ITEM_SUBCLASS_RECIPE_ENGINEERING         = 3,
   ITEM_SUBCLASS_RECIPE_BLACKSMITHING       = 4,
   ITEM_SUBCLASS_RECIPE_COOKING             = 5,
   ITEM_SUBCLASS_RECIPE_ALCHEMY             = 6,
   ITEM_SUBCLASS_RECIPE_FIRST_AID           = 7,
   ITEM_SUBCLASS_RECIPE_ENCHANTING          = 8,
   ITEM_SUBCLASS_RECIPE_FISHING             = 9,
   ITEM_SUBCLASS_RECIPE_JEWELCRAFTING       = 10,
   ITEM_SUBCLASS_RECIPE_INSCRIPTION         = 11, //Guessed

   // Quiver
   ITEM_SUBCLASS_QUIVER_QUIVER              = 2,
   ITEM_SUBCLASS_QUIVER_AMMO_POUCH          = 3,

   // Containers
   ITEM_SUBCLASS_CONTAINER                  = 0,
   ITEM_SUBCLASS_CONTAINER_SOUL             = 1,
   ITEM_SUBCLASS_CONTAINER_HERB             = 2,
   ITEM_SUBCLASS_CONTAINER_ENCHANTING       = 3,
   ITEM_SUBCLASS_CONTAINER_ENGINEERING      = 4,
   ITEM_SUBCLASS_CONTAINER_GEM              = 5,
   ITEM_SUBCLASS_CONTAINER_MINING           = 6,
   ITEM_SUBCLASS_CONTAINER_LEATHERWORKING   = 7,
   ITEM_SUBCLASS_CONTAINER_INSCRIPTION      = 8,

   // Consumable
   ITEM_SUBCLASS_CONSUMABLE                 = 0,
   ITEM_SUBCLASS_CONSUMABLE_POTION          = 1,
   ITEM_SUBCLASS_CONSUMABLE_ELIXIR          = 2,
   ITEM_SUBCLASS_CONSUMABLE_FLASK           = 3,
   ITEM_SUBCLASS_CONSUMABLE_SCROLL          = 4,
   ITEM_SUBCLASS_CONSUMABLE_FOOD            = 5,
   ITEM_SUBCLASS_CONSUMABLE_ITEM_ENCHANT    = 6,
   ITEM_SUBCLASS_CONSUMABLE_BANDAGE         = 7,
   ITEM_SUBCLASS_CONSUMABLE_OTHER           = 8,

   // Gem
   ITEM_SUBCLASS_GEM_RED                    = 0,
   ITEM_SUBCLASS_GEM_BLUE                   = 1,
   ITEM_SUBCLASS_GEM_YELLOW                 = 2,
   ITEM_SUBCLASS_GEM_PURPLE                 = 3,
   ITEM_SUBCLASS_GEM_GREEN                  = 4,
   ITEM_SUBCLASS_GEM_ORANGE                 = 5,
   ITEM_SUBCLASS_GEM_META                   = 6,
   ITEM_SUBCLASS_GEM_SIMPLE                 = 7,
   ITEM_SUBCLASS_GEM_PRISMATIC              = 8,

   // Trade goods
   ITEM_SUBCLASS_TRADE_GOODS                = 0,
   ITEM_SUBCLASS_PROJECTILE_PARTS           = 1,
   ITEM_SUBCLASS_PROJECTILE_EXPLOSIVES      = 2,
   ITEM_SUBCLASS_PROJECTILE_DEVICES         = 3,
   ITEM_SUBCLASS_JEWELCRAFTING              = 4,
   ITEM_SUBCLASS_CLOTH                      = 5,
   ITEM_SUBCLASS_LEATHER                    = 6,
   ITEM_SUBCLASS_METAL_STONE                = 7,
   ITEM_SUBCLASS_MEAT                       = 8,
   ITEM_SUBCLASS_HERB                       = 9,
   ITEM_SUBCLASS_ELEMENTAL                  = 10,
   ITEM_SUBCLASS_TRADE_GOODS_OTHER          = 11,
   ITEM_SUBCLASS_ENCHANTING                 = 12,
   ITEM_SUBCLASS_MATERIAL                   = 13,
   ITEM_SUBCLASS_ARMOR_ENCHANTMENT          = 14,
   ITEM_SUBCLASS_WEAPON_ENCHANTMENT         = 15,

   //Glyph
   ITEM_SUBCLASS_GLYPH_WARRIOR              = 1,
   ITEM_SUBCLASS_GLYPH_PALADIN              = 2,
   ITEM_SUBCLASS_GLYPH_HUNTER               = 3,
   ITEM_SUBCLASS_GLYPH_ROGUE                = 4,
   ITEM_SUBCLASS_GLYPH_PRIEST               = 5,
   ITEM_SUBCLASS_GLYPH_DEATH_KNIGHT         = 6,
   ITEM_SUBCLASS_GLYPH_SHAMAN               = 7,
   ITEM_SUBCLASS_GLYPH_MAGE                 = 8,
   ITEM_SUBCLASS_GLYPH_WARLOCK              = 9,
   ITEM_SUBCLASS_GLYPH_DRUID                = 11,

   // Key
   ITEM_SUBCLASS_KEY                        = 0,
   ITEM_SUBCLASS_LOCKPICK                   = 1,

   // MISCELLANEOUS
   ITEM_SUBCLASS_MISCELLANEOUS              = 0,
   ITEM_SUBCLASS_MISCELLANEOUS_REAGENT      = 1,
   ITEM_SUBCLASS_MISCELLANEOUS_PET          = 2,
   ITEM_SUBCLASS_MISCELLANEOUS_HOLIDAY      = 3,
   ITEM_SUBCLASS_MISCELLANEOUS_OTHER        = 4,
   ITEM_SUBCLASS_MISCELLANEOUS_MOUNT        = 5,
};

enum ITEM_QUALITY
{
    ITEM_QUALITY_POOR_GREY             = 0,
    ITEM_QUALITY_NORMAL_WHITE          = 1,
    ITEM_QUALITY_UNCOMMON_GREEN        = 2,
    ITEM_QUALITY_RARE_BLUE             = 3,
    ITEM_QUALITY_EPIC_PURPLE           = 4,
    ITEM_QUALITY_LEGENDARY_ORANGE      = 5,
    ITEM_QUALITY_ARTIFACT_LIGHT_YELLOW = 6,
    ITEM_QUALITY_DBC_MAX               = 7
};

enum ITEM_FLAG
{
    ITEM_FLAG_SOULBOUND     = 0x1,      // not used in proto
    ITEM_FLAG_CONJURED      = 0x2,
    ITEM_FLAG_LOOTABLE      = 0x4,
    ITEM_FLAG_WRAPPED       = 0x8,      // not used in proto
    ITEM_FLAG_UNKNOWN_05    = 0x10,     // many equipable items and bags
    ITEM_FLAG_UNKNOWN_06    = 0x20,     // totems
    ITEM_FLAG_UNKNOWN_07    = 0x40,     // many consumables
    ITEM_FLAG_UNKNOWN_08    = 0x80,     // only 1 wand uses this
    ITEM_FLAG_UNKNOWN_09    = 0x100,    // some wands & relics
    ITEM_FLAG_WRAP_GIFT     = 0x200,
    ITEM_FLAG_CREATE_ITEM   = 0x400,
    ITEM_FLAG_QUEST         = 0x800,
    ITEM_FLAG_UNKNOWN_13    = 0x1000,   // not used in proto
    ITEM_FLAG_SIGNABLE      = 0x2000,
    ITEM_FLAG_READABLE      = 0x4000,
    ITEM_FLAG_UNKNOWN_16    = 0x8000,
    ITEM_FLAG_EVENT_REQ     = 0x10000,
    ITEM_FLAG_UNKNOWN_18    = 0x20000,
    ITEM_FLAG_PROSPECTABLE  = 0x40000,
    ITEM_FLAG_UNIQUE_EQUIP  = 0x80000,
    ITEM_FLAG_UNKNOWN_21    = 0x100000, // not used in proto
    ITEM_FLAG_UNKNOWN_22    = 0x200000, // player created health/mana
    ITEM_FLAG_THROWN        = 0x400000,
    ITEM_FLAG_SHAPESHIFT_OK = 0x800000,
    ITEM_FLAG_BINDONACC     = 0x8000000, // bind on account
    ITEM_FLAG_MILLABLE      = 0x20000000
};

enum SPECIAL_ITEM_TYPE
{
    ITEM_TYPE_BOWAMMO       = 1,    // Arrows
    ITEM_TYPE_GUNAMMO       = 2,    // Bullets
    ITEM_TYPE_SOULSHARD     = 4,    // Soul Shards
    ITEM_TYPE_LEATHERWORK   = 8,    // Leatherworking Supplies
    ITEM_TYPE_INSCRIPTION   = 16,   // Inscripton Supplies
    ITEM_TYPE_HERBALISM     = 32,   // Herbs
    ITEM_TYPE_ENCHANTMENT   = 64,   // Enchanting Supplies
    ITEM_TYPE_ENGINEERING   = 128,  // Engineering Supplies
    ITEM_TYPE_KEYRING       = 256,  // Keys
    ITEM_TYPE_GEMS          = 512,  // Gems
    ITEM_TYPE_MINING        = 1024, // Mining Supplies
    ITEM_TYPE_SBEQUIPMENT   = 2048, // Soulbound Equipment
    ITEM_TYPE_VANITYPETS    = 4096, // Vanity Pets
    ITEM_TYPE_CURRENCY      = 8192,
    ITEM_TYPE_QUEST_ITEMS   = 16384
};

enum SOCKET_GEM_COLOR
{
    META_SOCKET = 1,
    RED_SOCKET = 2,
    YELLOW_SOCKET = 4,
    BLUE_SOCKET = 8
};
